# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: deploy-model-training-pipeline

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      # 'main' branch: PRD environment
      - template: ../../config-infra-prod.yml
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      # 'develop' or feature branches: DEV environment
      - template: ../../config-infra-dev.yml
  - name: version
    value: aml-cli-v2

trigger: none

pool:
  vmImage: ubuntu-20.04

resources:
  repositories:
    - repository: insurance-cost
      name: insurance-cost
      type: git
      ref: main

stages:
  - stage: DeployTrainingPipeline
    displayName: Deploy Training Pipeline
    jobs:
      - job: DeployTrainingPipeline
        timeoutInMinutes: 120 # how long to run the job before automatically cancelling
        steps:
          - checkout: self
            path: s/
          - task: Bash@3
            displayName: "Prevent repos dir warnings"
            inputs:
              targetType: "inline"
              script: |
                set -e
                if [ ! -d "$(Build.Repository.Name)" ]; then
                  mkdir -p "$(Build.Repository.Name)"
                fi
                if [ ! -d "insurance-cost" ]; then
                  mkdir -p "insurance-cost"
                fi
          - checkout: insurance-cost
            path: s/templates/
          - template: templates/${{ variables.version }}/install-az-cli.yml@insurance-cost
          - template: templates/${{ variables.version }}/install-aml-cli.yml@insurance-cost
          - template: templates/${{ variables.version }}/connect-to-workspace.yml@insurance-cost
          - template: templates/${{ variables.version }}/register-environment.yml@insurance-cost
            parameters:
              environment_name: insurance-train-env
              environment_file: mlops/azureml/train/train-env.yml
          - template: templates/${{ variables.version }}/create-compute.yml@insurance-cost
            parameters:
              cluster_name: cpu-cluster
              size: Standard_DS3_v2
              min_instances: 0
              max_instances: 4
              cluster_tier: low_priority
          - template: templates/${{ variables.version }}/register-data.yml@insurance-cost
            parameters:
              data_type: uri_file
              data_name: insurance-data
              data_file: mlops/azureml/train/data.yml
          - template: templates/${{ variables.version }}/run-pipeline.yml@insurance-cost
            parameters:
              pipeline_file: mlops/azureml/train/pipeline.yml
              experiment_name: $(environment)_insurance_charge_train_$(Build.SourceBranchName)
              display_name: $(environment)_insurance_charge_run_$(Build.BuildID)
              enable_monitoring: $(enable_monitoring)
