# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: deploy-online-endpoint-pipeline

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      # 'main' branch: PRD environment
      - template: ../../config-infra-prod.yml
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      # 'develop' or feature branches: DEV environment
      - template: ../../config-infra-dev.yml
  - name: version
    value: aml-cli-v2
  - name: endpoint_name
    value: insurance-online-$(namespace)$(postfix)$(environment)
  - name: endpoint_type
    value: online

trigger: none

pool:
  vmImage: ubuntu-20.04

resources:
  repositories:
    - repository: insurance-cost # Template Repo
      name: insurance-cost
      type: git
      ref: main

stages:
  - stage: CreateOnlineEndpoint
    displayName: Create/Update Online Endpoint
    jobs:
      - job: DeployOnlineEndpoint
        steps:
          - checkout: self
            path: s/
          - task: Bash@3
            displayName: "Create checkout repository folder(s)"
            inputs:
              targetType: "inline"
              script: |
                set -e
                mkdir "$(Build.Repository.Name)"
                mkdir "insurance-cost"
          - checkout: insurance-cost
            path: s/templates/
          - template: templates/${{ variables.version }}/install-az-cli.yml@insurance-cost
          - template: templates/${{ variables.version }}/install-aml-cli.yml@insurance-cost
          - template: templates/${{ variables.version }}/connect-to-workspace.yml@insurance-cost
          - template: templates/${{ variables.version }}/create-endpoint.yml@insurance-cost
            parameters:
              endpoint_file: mlops/azureml/deploy/online/online-endpoint.yml
          - template: templates/${{ variables.version }}/create-deployment.yml@insurance-cost
            parameters:
              deployment_name: insurance-online-dp
              deployment_file: mlops/azureml/deploy/online/online-deployment.yml
          - template: templates/${{ variables.version }}/allocate-traffic.yml@insurance-cost
            parameters:
              traffic_allocation: insurance-online-dp=100
          - template: templates/${{ variables.version }}/test-deployment.yml@insurance-cost
            parameters:
              deployment_name: insurance-online-dp
              sample_request: data/insurance-request.json
              request_type: json
